<template>
<div class="show-module-content" style="display: none; width: 88%;">
     <iframe id="meditacija" width="100%" height="175" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/705514984&color=%23f41256&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true"></iframe>
</iframe>
</div>
</template>
<script>
export default {
    mounted() {
        console.log('Mounted!');
    }
}
</script>